version: '3.8'

services:
  openldap:
    image: bitnami/openldap:2.6.10
    container_name: openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_USERS=user01,user02,user03
      - LDAP_PASSWORDS=password1,password2,password3
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org 
      #- LDAP_USER_DC=users
      - LDAP_GROUP=readers
    ports:
      - "1389:1389"
      - "1636:1636"
    volumes:
      - openldap_data:/bitnami/openldap
    networks:
      - openldap

volumes:
  openldap_data:
    driver: local

networks:
  openldap:
    driver: bridge